name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout K3s
        uses: actions/checkout@v3
      - name: Build K3s binary
        run: |
          DOCKER_BUILDKIT=1 SKIP_AIRGAP=1 SKIP_VALIDATE=1 make
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/artifacts/*